services:
  db:
    restart: always
    image: mysql:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-mysql
    environment:
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=IotAdmin
    volumes:
      - ${DB_DIR_MYSQL}:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 120s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  api:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-api:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ApiConfiguration__Environment=${ENVIRONMENT}
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=MySql
      - ApiConfiguration__Repository__MySql__Url=Server=${COMPOSE_PROJECT_NAME}_iot-admin-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotAdmin
      - ApiConfiguration__Modules__Gpio__Type=${GPIO}
    ports:
      - ${API_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-web:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - WebConfiguration__Environment=${ENVIRONMENT}
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=MySql
      - WebConfiguration__Repository__MySql__Url=Server=${COMPOSE_PROJECT_NAME}_iot-admin-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotAdmin
      - WebConfiguration__Api__Url=http://${COMPOSE_PROJECT_NAME}_iot-admin-api:8080
    ports:
      - ${WEB_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

networks:
  iot-admin:
    driver: bridge