services:
  db:
    restart: always
    image: mongo:latest
    container_name: iot-admin-mongodb
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ${DB_DIR}:/data/db
    ports:
      - 27009:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 120s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  api:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-api:latest
    container_name: iot-admin-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__Environment=Development
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=MongoDb
      - ApiConfiguration__Repository__MongoDb__Url=mongodb://iot-admin-mongodb:27017
      - ApiConfiguration__Modules__Gpio__Type=Mock
    ports:
      - 8000:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-web:latest
    container_name: iot-admin-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - WebConfiguration__Environment=Development
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=MongoDb
      - WebConfiguration__Repository__MongoDb__Url=mongodb://iot-admin-mongodb:27017
      - WebConfiguration__Api__Url=http://iot-admin-api:8080
    ports:
      - 8005:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  mongoexpress:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: mongo-express:latest
    container_name: iot-admin-mongoexpress
    environment:
      - TZ=Europe/Warsaw
      - ME_CONFIG_MONGODB_SERVER=iot-admin-mongodb
    ports:
      - 8009:8081
    tty: true
    privileged: true
    networks:
      - iot-admin

networks:
  iot-admin:
    driver: bridge