services:
  db:
    restart: always
    image: mysql:latest
    container_name: iot-admin-mysql
    environment:
      - TZ=Europe/Warsaw
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=IotAdmin
    volumes:
      - ${DB_DIR}:/var/lib/mysql
    ports:
      - 3309:3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  api:
    depends_on:
      db:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-api:latest
    container_name: iot-admin-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiConfiguration__Environment=Development
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=MySql
      - ApiConfiguration__Repository__MySql__Url=Server=iot-admin-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotAdmin
      - ApiConfiguration__Modules__Gpio__Type=Mock
    ports:
      - 8000:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-web:latest
    container_name: iot-admin-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=Development
      - WebConfiguration__Environment=Development
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=MySql
      - WebConfiguration__Repository__MySql__Url=Server=iot-admin-mysql;Port=3306;User ID=root;Password=${DB_PWD};Database=IotAdmin
      - WebConfiguration__Api__Url=http://iot-admin-api:8080
    ports:
      - 8005:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

networks:
  iot-admin:
    driver: bridge