services:
  api:
    restart: always
    image: qbituniverse/iot-admin-api:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-api
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ApiConfiguration__Environment=${ENVIRONMENT}
      - ApiConfiguration__LogLevel__Console=Information
      - ApiConfiguration__LogLevel__Database=Error
      - ApiConfiguration__Repository__Type=SQLite
      - ApiConfiguration__Repository__SQLite__Url=/data/db/IotAdmin.db
      - ApiConfiguration__Modules__Gpio__Type=${GPIO}
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${API_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin
  
  web:
    depends_on:
      api:
        condition: service_healthy
    restart: always
    image: qbituniverse/iot-admin-web:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-web
    environment:
      - TZ=Europe/Warsaw
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - WebConfiguration__Environment=${ENVIRONMENT}
      - WebConfiguration__LogLevel__Console=Information
      - WebConfiguration__LogLevel__Database=Error
      - WebConfiguration__Repository__Type=SQLite
      - WebConfiguration__Repository__SQLite__Url=/data/db/IotAdmin.db
      - WebConfiguration__Api__Url=http://${COMPOSE_PROJECT_NAME}_iot-admin-api:8080
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${WEB_PORT}:8080
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 30s
      timeout: 30s
      retries: 10
    tty: true
    privileged: true
    networks:
      - iot-admin

  sqlitebrowser:
    depends_on:
      web:
        condition: service_healthy
    restart: always
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: ${COMPOSE_PROJECT_NAME}_iot-admin-sqlitebrowser
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Europe/Warsaw
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DB_DIR_SQLITE}:/data/db
    ports:
      - ${DB_PORT}:3000
    tty: true
    privileged: true
    networks:
      - iot-admin

networks:
  iot-admin:
    driver: bridge