FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

LABEL version="8.0" \
	  description="Image to create IoT Admin API" \
	  maintainer="marcin.narloch@qbituniverse.com"

WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["IoT.Admin.Api/IoT.Admin.Api.csproj", "IoT.Admin.Api/"]
RUN dotnet restore "IoT.Admin.Api/IoT.Admin.Api.csproj"

COPY . .
WORKDIR "/src/IoT.Admin.Api"
RUN dotnet build "IoT.Admin.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IoT.Admin.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "IoT.Admin.Api.dll"]